### ISSUE TITLE
Kubernetes Provider invalid certificate

### ISSUE THREAD

**Issue by SouthernYoda** [hashicorp/learn-terraform-provision-gke-cluster#1]
I am following the "Manage Kubernetes Resources via Terraform" guide. I create the cluster using this repo. I added the kubernetes.tf file with the Kubernetes provider getting credentials via variables.

kubernetes.tf
```provider "kubernetes" {
  load_config_file = false

  host      = google_container_cluster.primary.endpoint
  username  = var.gke_username
  password  = var.gke_password

  client_certificate      = google_container_cluster.primary.master_auth.0.client_certificate
  client_key              = google_container_cluster.primary.master_auth.0.client_key
  cluster_ca_certificate  = google_container_cluster.primary.master_auth.0.cluster_ca_certificate
}
```

I get the below error when I try to create a resource using the Kubernetes provider:

```Error: Failed to create deployment: Post "https://<gcp_ip>apis/apps/v1/namespaces/default/deployments": x509: certificate signed by unknown authority```

When I navigate in my browser the certificate is not trusted but once I allow the browser exception I am able to navigate to the page.

**Comment by ggmartins** [comment]
had the same problem. Not sure if this was the exact fix for it but if you want to try this one out:

`cluster_ca_certificate = base64decode(google_container_cluster.primary.master_auth.0.cluster_ca_certificate)`

**Comment by im2nguyen** [comment]
Closing this out because we updated best practices on how to auth to the GKE cluster using the kubernetes provider. You should not manage the kubernetes resources in the same workspace/directory as you provision your GKE cluster

You can find more information here: https://learn.hashicorp.com/tutorials/terraform/kubernetes-provider?in=terraform/kubernetes

This is a sample snippet of how you can manage resources in a GKE cluster:

```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.52.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.1"
    }
  }
}

data "terraform_remote_state" "gke" {
  backend = "local"

  config = {
    path = "../learn-terraform-provision-gke-cluster/terraform.tfstate"
  }
}

# Retrieve GKE cluster information
provider "google" {
  project = data.terraform_remote_state.gke.outputs.project_id
  region  = data.terraform_remote_state.gke.outputs.region
}

# Configure kubernetes provider with Oauth2 access token.
# https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config
# This fetches a new token, which will expire in 1 hour.
data "google_client_config" "default" {}

data "google_container_cluster" "my_cluster" {
  name     = data.terraform_remote_state.gke.outputs.kubernetes_cluster_name
  location = data.terraform_remote_state.gke.outputs.region
}

provider "kubernetes" {
  host = data.terraform_remote_state.gke.outputs.kubernetes_cluster_host

  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.my_cluster.master_auth[0].cluster_ca_certificate)
}
```
