### ISSUE TITLE
`provider` section is missing credentials

### ISSUE THREAD

**Issue by sed-i** [hashicorp/learn-terraform-provision-gke-cluster#18]
The `provider` section in the template is missing credentials:

https://github.com/hashicorp/learn-terraform-provision-gke-cluster/blob/5f4fac43f8b0e8ad66b75dd24cf5632fd0d7f015/vpc.tf#L9-L12

without which tf errors out:

```
│ Error: Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'.  Original error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
│ 
│   with provider["registry.terraform.io/hashicorp/google"],
│   on vpc.tf line 9, in provider "google":
│    9: provider "google" {
```

and it's not mentioned in the [docs](https://developer.hashicorp.com/terraform/tutorials/kubernetes/gke).

**Comment by judithpatudith** [comment]
Hi! did you [authenticate with the cloud SDK](https://developer.hashicorp.com/terraform/tutorials/kubernetes/gke#prerequisites)? That's where the provider should get your credentials from. If you did that and still got an error please let me know so I can get the tutorial fixed up! Thanks for the report!
