### ISSUE TITLE
The outputs.tf is missing VPC entries

### ISSUE THREAD

**Issue by wagsandre** [hashicorp/learn-terraform-provision-gke-cluster#5]
To deploy GKE cluster is necessary to declare the network and subnetwork values in the `outputs.tf` file, as the example below. The values are necessary to the resource `google_container_cluster` defined in the `gke.tf` file.

```
output "network" {
 value = google_compute_network.vpc.self_link
 description = "GKE VPC Network"
}

output "subnetwork" {
 value = google_compute_subnetwork.subnet.self_link
 description = "GKE VPC Subnet"
}
```

**Comment by im2nguyen** [comment]
Hi @wagsandre, can you elaborate why these two outputs are needed? In [`gke.tf`](https://github.com/hashicorp/learn-terraform-provision-gke-cluster/blob/master/gke.tf#L24-L25) already deploy it to the VPC and subnets created in this tutorial.

```
resource "google_container_cluster" "primary" {
    ## ...

  network    = google_compute_network.vpc.name
  subnetwork = google_compute_subnetwork.subnet.name
  
  ## ...
}
```

**Comment by wagsandre** [comment]
Hi @im2nguyen. Ok, understood. I believe it was my mistake in confuse the resource configuration from a different file as they were in a module. But ok, they aren't in a module. So doesn't make sense to configure them in `outputs.tf`. However the `google_container_cluster` expect to have the argument `network` as the `self_link` value rather than `name`. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#network

The same applies to `subnetwork` argument.

In my test, it just worked like that.

**Comment by im2nguyen** [comment]
Hi @wagsandre,

Is `name` not working for network and subnetwork? Name _should_ work based on the documentation and when I tested this configuration.

1. `**network**`: (Optional) The name or self_link of the Google Compute Engine network to which the cluster is connected. For Shared VPC, set this to the self link of the shared network.
2. `**subnetwork**`:  (Optional) The name or self_link of the Google Compute Engine subnetwork in which the cluster's instances are launched.

**Comment by wagsandre** [comment]
Hi @im2nguyen , understand, but the mine didn't work with `name` and I'm not using Shared VPC.

**Comment by im2nguyen** [comment]
Hi @wagsandre , that's interesting, can you provide the error message you're receiving?

**Comment by wagsandre** [comment]
> Hi @wagsandre , that's interesting, can you provide the error message you're receiving?

Not facing the error anymore =/

**Comment by im2nguyen** [comment]
I think not facing the error should be 😄 , not =/ 

😛

**Comment by wagsandre** [comment]
😁
Weird that the error just pointed out to the line of the network block, but didn't show any detail. Unfortunately I didn't save the message error.
