### ISSUE TITLE
Does not work with 1.0.3

### ISSUE THREAD

**Issue by codefrau** [hashicorp/learn-terraform-provision-gke-cluster#7]
│ Error: Unsupported Terraform Core version
│ 
│   on versions.tf line 9, in terraform:
│    9:   required_version = "~> 0.14"
│ 
│ This configuration does not support Terraform version 1.0.3. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

**Comment by MichaelCade** [comment]
> 
> 
> │ Error: Unsupported Terraform Core version
> │
> │ on versions.tf line 9, in terraform:
> │ 9: required_version = "~> 0.14"
> │
> │ This configuration does not support Terraform version 1.0.3. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.
> ╵

I had the same issue as @codefrau I made an edit to the versions.tf 

original = required_version = "~> 0.14"
modified = required_version = "> 0.14"

hope that helps everyone get things up and running here. 

I am using Terraform version v1.0.4, with the above change terraform init then works.

**Comment by im2nguyen** [comment]
Sorry for the late response. I updated the repo to reflect this, thanks @MichaelCade !
